version = 0.1
[default.deploy.parameters]
stack_name = "CryptoInvestmentStack"
resolve_s3 = true
s3_prefix = "CryptoInvestmentStack"
region = "us-east-1"
profile = "yggdrasil"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
